version: '3.8'

services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # Mount the existing settings
      - ./searxng-settings.yml:/etc/searxng/settings.yml:ro
      # Mount custom static files (CSS, images, etc.)
      - ./searxng-custom/static:/usr/local/searxng/searx/static/themes/simple/custom:ro
      # Optional: Mount custom templates
      # - ./searxng-custom/templates:/usr/local/searxng/searx/templates/simple/custom:ro
    environment:
      - SEARXNG_BASE_URL=https://search.theronlindsay.dev/
      - SEARXNG_SECRET=bRQ7GVid5Lrd33wJXqZg1JvXSTLGcnDj
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
